import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NavbarPage from '@/components/navbar/navbar';
import { Toaster } from '@/components/ui/sonner';
import Footer05Page from '@/components/footer-05/footer-05';
import { AuthProvider } from '@/context/AuthProvider';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  weight: ['300', '400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='es'>
      <body className={`${inter.className} antialiased relative`}>
        <AuthProvider>
          <NavbarPage />
          <main>{children}</main>
        </AuthProvider>
        <Toaster richColors />
        <Footer05Page />
      </body>
    </html>
  );
}
